import{a as L,S as b,i}from"./assets/vendor-CZwys2ms.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const h of s.addedNodes)h.tagName==="LINK"&&h.rel==="modulepreload"&&o(h)}).observe(document,{childList:!0,subtree:!0});function a(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function o(e){if(e.ep)return;e.ep=!0;const s=a(e);fetch(e.href,s)}})();const g=r=>`  
      <li class="gallery-card">
      <a href="${r.largeImageURL}">
        <img class="gallery-img" src="${r.webformatURL}" alt="${r.tags}" />
      </a>
      <div class="gallery-info">
        <p><b>Likes</b> ${r.likes}</p>
        <p><b>Views</b> ${r.views}</p>
        <p><b>Comments</b> ${r.comments}</p>
        <p><b>Downloads</b> ${r.downloads}</p>
      </div>
    </li>
  `,x="https://pixabay.com/api/",f=async(r,t=1,a=15)=>{try{const o={params:{key:"45489972-425dbd0ae29bdd8e452daca41",q:r,image_type:"photo",orientation:"horizontal",safesearch:"true",page:t,per_page:a}};return(await L.get(`${x}`,o)).data}catch(o){throw new Error(o.response.status)}},p=document.querySelector(".search-form"),u=document.querySelector(".gallery"),n=document.querySelector(".loader"),d=document.querySelector(".load-more-btn");let y=new b(".gallery a"),l=1,c="",m=0;const v=async r=>{if(r.preventDefault(),c=p.elements.user_query.value.trim(),!c){i.error({message:"Please enter a valid search query!",position:"topRight",maxWidth:"500px"});return}l=1,d.classList.add("is-hidden"),n.classList.remove("is-hidden");try{const t=await f(c,l);if(n.classList.add("is-hidden"),t.hits.length===0){i.error({message:"Sorry, there are no images matchings your search query. Please try againe!",position:"topRight",maxWidth:"500px"}),u.innerHTML="",p.reset();return}m=t.totalHits;const a=t.hits.map(o=>g(o)).join("");u.innerHTML=a,y.refresh(),l*15>=m?i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight",maxWidth:"500px"}):d.classList.remove("is-hidden")}catch{console.log(err),i.error({message:"Something went wrong. Please try again later!",position:"topRight",maxWidth:"500px"}),n.classList.add("is-hidden")}},w=async r=>{l++,n.classList.remove("is-hidden");try{const t=await f(c,l);n.classList.add("is-hidden");const a=t.hits.map(o=>g(o)).join("");u.insertAdjacentHTML("beforeend",a),y.refresh(),l*15>=m&&(d.classList.add("is-hidden"),i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight",maxWidth:"500px"}))}catch(t){console.log(t),i.error({message:"Something went wrong. Please try again later!",position:"topRight",maxWidth:"500px"}),n.classList.add("is-hidden")}};p.addEventListener("submit",v);d.addEventListener("click",w);
//# sourceMappingURL=index.js.map
