import{a as b,S as v,i}from"./assets/vendor-CZwys2ms.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const p of s.addedNodes)p.tagName==="LINK"&&p.rel==="modulepreload"&&o(p)}).observe(document,{childList:!0,subtree:!0});function a(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function o(e){if(e.ep)return;e.ep=!0;const s=a(e);fetch(e.href,s)}})();const g=r=>`  
      <li class="gallery-card">
      <a href="${r.largeImageURL}">
        <img class="gallery-img" src="${r.webformatURL}" alt="${r.tags}" />
      </a>
      <div class="gallery-info">
        <p><b>Likes</b> ${r.likes}</p>
        <p><b>Views</b> ${r.views}</p>
        <p><b>Comments</b> ${r.comments}</p>
        <p><b>Downloads</b> ${r.downloads}</p>
      </div>
    </li>
  `,x="https://pixabay.com/api/",y=async(r,t=1,a=15)=>{try{const o={params:{key:"45489972-425dbd0ae29bdd8e452daca41",q:r,image_type:"photo",orientation:"horizontal",safesearch:"true",page:t,per_page:a}};return(await b.get(`${x}`,o)).data}catch(o){throw new Error(o.response.status)}},u=document.querySelector(".search-form"),c=document.querySelector(".gallery"),n=document.querySelector(".loader"),h=document.querySelector(".load-more-btn");let f=new v(".gallery a"),l=1,d="",m=0,L=0;const w=async r=>{if(r.preventDefault(),d=u.elements.user_query.value.trim(),!d){i.error({message:"Please enter a valid search query!",position:"topRight",maxWidth:"500px"});return}l=1,h.classList.add("is-hidden"),n.classList.remove("is-hidden");try{const t=await y(d,l);if(n.classList.add("is-hidden"),t.hits.length===0){i.error({message:"Sorry, there are no images matchings your search query. Please try againe!",position:"topRight",maxWidth:"500px"}),c.innerHTML="",u.reset();return}m=t.totalHits;const a=t.hits.map(e=>g(e)).join("");c.innerHTML=a,L=c.querySelector("li").getBoundingClientRect().height,f.refresh(),l*15>=m?i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight",maxWidth:"500px"}):h.classList.remove("is-hidden")}catch{console.log(err),i.error({message:"Something went wrong. Please try again later!",position:"topRight",maxWidth:"500px"}),n.classList.add("is-hidden")}},S=async r=>{l++,n.classList.remove("is-hidden");try{const t=await y(d,l);n.classList.add("is-hidden");const a=t.hits.map(o=>g(o)).join("");c.insertAdjacentHTML("beforeend",a),f.refresh(),scrollBy({top:L*2,behavior:"smooth"}),l*15>=m&&(h.classList.add("is-hidden"),i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight",maxWidth:"500px"}))}catch(t){console.log(t),i.error({message:"Something went wrong. Please try again later!",position:"topRight",maxWidth:"500px"}),n.classList.add("is-hidden")}};u.addEventListener("submit",w);h.addEventListener("click",S);
//# sourceMappingURL=index.js.map
